name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Push
        env:
          push: ${{ secrets.LOUIS_PUSH }}
        run: | 
          echo "uwu"
          #git clone https://github.com/niklasCarstensen/Discord-Bot
          #cd Discord-Bot
          #git push https://$push@git.bre4k3r.de/dev-bre4k3r/Discord-Bot
