name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Push
        env:
          push: ${{ secrets.LOUIS_PUSH }}
        run: | 
          echo "uwu"
          #git push https://$push@git.bre4k3r.de/dev-bre4k3r/Discord-Bot
